### PR TITLE
Add new feature that check whether http:// urls actually work using https://

### PR DESCRIPTION
**Pull request by hyunjiLeeTech**
Hi Leon,

I have completed the new feature that allows users to check whether http:// urls actually work using https:// with the argument -s.

For example,
testLink -s test1.html
will check both http:// and https:// for the http:// urls.

Can you please have a look at it?

Thanks.

### CODE REVIEW

**Review by lixiaoqity — COMMENTED** [review]
Thank you. It is a good way to check whether http:// URLs actually work using https://. 
In line 33, "data = fs.readFileSync(fileName[i++], 'utf8');",  I don't think we can use i++. Because the for loop has used it.

**Comment by hyunjiLeeTech** [comment]
I've fixed the thing you mention. Can you please check it?

**Comment by lixiaoqity** [comment]
> I've fixed the thing you mention. Can you please check it?
Thank you for your help.

**Review by lixiaoqity — APPROVED** [review]
Accept the changes

**Pull request merged**
